### ISSUE TITLE
Special Marth dps wrong

### ISSUE THREAD

**Issue by SanyamBansal** [b1ueb1ues/dl#13]
His S2 should not be doing that much damage if he's missing the damage portion.
The team buff seems really low considering its a 30% aspd(also gives more SP) and str buff.

**Comment by b1ueb1ues** [comment]
the damage is a problem.
but str and spd buff seems work correctly, 
Marth vs Elisanne
(30spd+10att) * 10s  vs  20att * 21.75s
It's not as good as elisanne and need double sp.
