### ISSUE TITLE
Adding Def Up buff to G!Ranzal and 5T3 Wind Sword?

### ISSUE THREAD

**Issue by Dama624** [b1ueb1ues/dl#14]
Would it be possible to add the Def Up effect to G!Ranzal's Skill2 & the 5T3 Wind sword Durandal? I'd like to see if Resounding Rendition or Valiant Crown is a better print to run with G!Ranzal.

**Comment by b1ueb1ues** [comment]
why not shining overlord + Hospitality

**Comment by tinder-jpark** [comment]
I don't think the Dragon Claw 2nd ability on Shining Overlord is actually that useful because I don't know how long battles last after the 2nd/3rd transform

**Comment by b1ueb1ues** [comment]
this is a 
40%sd + 8%cc + doublebuff  + 15str
vs
40%sd + 8%str + doublebuff + dragon claw

I think dragon claw is at least better  than just 15str even if you only shift dragon once in the middle of the fight

**Comment by tinder-jpark** [comment]
I was thinking RR+Stellar Show or VC+Stellar Show
30% sd + 8%cc + 50%fs + 15%cd
30%sd + doublebuff + 50%fs + 15%cd

vs. Shining Overlord + Hospitality
40%sd + dragon claw + doublebuff + 8% str

**Comment by b1ueb1ues** [comment]
If you dragon once at middle of the fight and no lowen's def buff
hospitality+shining overlord > VC+hospitality(will lose 5% doublebuff) > VC+FP > RR+hospitality > VC+stellar
