### ISSUE TITLE
Lance Combos

### ISSUE THREAD

**Issue by emrysduvent** [b1ueb1ues/dl#17]
In general, it seems that a lot of lance adventurers do more damage (Elisanne - 2933 dps, H Elisanne - 2409, Fjorm - 1827, Botan - harder to judge due to bleed but it seems higher for my few trials) if they use damaging/offensive team buff skills when they are up and doing 5c+fs otherwise.

Ie: 
```
`s1
`s2
`s3
`fs, seq=5
```

Is this correct or due to some bug in the simulator/timings?

**Comment by b1ueb1ues** [comment]
it seems like a better action priority
