### ISSUE TITLE
Weapon skill buff duration not increased by passives (g_sarisse)

### ISSUE THREAD

**Issue by Totakeke** [b1ueb1ues/dl#2]
```
23.583  : cast      , s3                , 0         , <cast> 1495/2803, 7475/8534, 0/7316 (s3 after c5)
23.583  : buff      , s3                , crit: 0.25    , s3 buff start <10s>
```

Saw this for g_sarisse.py while trying out your code (really cool stuff btw).

Buff time should be multiplied by her 30% buff time passive like the other buffs unless you verified it to be otherwise

**Comment by b1ueb1ues** [comment]
Though I don't have shirisu to test about that, I guess you are right.
Fixed it.
