### ISSUE TITLE
Charging FS during skill animation

### ISSUE THREAD

**Issue by haukist** [b1ueb1ues/dl#23]
It was introduced in v1.8.0 but it's not implemented in the simulator yet?

> When using a skill, it is now possible to switch to charging force strikes during the cut-in animation, as long as the skill's motion is complete.

`https://dragalialost.com/en/news/detail/480`

**Comment by b1ueb1ues** [comment]
1: this bug was not implemented in the simulator in the begining.
2: who are you expected to use that feature to lower their dps?
3. you can't 'Charging FS during skill animation' like always

**Comment by haukist** [comment]
I'm sorry, I used sx=1 instead of s=1. I was testing how it affects DPS. Thank you for your response.
