### ISSUE TITLE
".charged" acl isn't behaving properly

### ISSUE THREAD

**Issue by Totakeke** [b1ueb1ues/dl#3]
```
=======================
1528(0.00) , Kleimann (str: 2720)  ;
-----------------------
dmgsum     | {'total': '275211', 'x': '116157', 's': '157848', 'fs': '1206', 'others': '0'}
skill_stat | {'s3': '0 (0)', 's2': '34902 (6)', 's1': '122947 (18)'}
x_stat     | {'fs': 1, 'x5': 36}

```
```
=======================
1811(0.04) , G_Sarisse (str: 2720)  ;c4+fs
-----------------------
dmgsum     | {'total': '326070', 'x': '81753', 's': '195730', 'fs': '48586', 'others': '0'}
skill_stat | {'s3': '0 (0)', 's2': '0 (5)', 's1': '195730 (18)'}
x_stat     | {'fs': 36, 'x4': 36}
```

Don't know your code enough to fix these yet, but it looks like the acl definition isn't behaving as you intended for conditional skills based on other skills charging.
Kleinmann isn't using fs, G_Sarisse c4+fs isn't using s3.

**Comment by b1ueb1ues** [comment]
change g_sarisse to
```
        `s3,s1.charged>=2803
        `s1
        `s2
        `fs, seq=4
```
that works, 
I used to put s3 after s1. s1 had more priority than s3, so s3 won't work. Every time s1 is charged, s1 will trigger.

kleinmann's fs work very little condition is intended, just to change a little his action sequences to increase DPS, but I actually don't know why add 1 fs will increase dps that much

**Comment by b1ueb1ues** [comment]
I think .charged  work well.
to see addis.py
