### ISSUE TITLE
Sarisse combos

### ISSUE THREAD

**Issue by haukist** [b1ueb1ues/dl#34]
You can't keep combos if you FS after S1.

**Comment by haukist** [comment]
The same goes for Laranoa.

**Comment by b1ueb1ues** [comment]
but I can keep sarisse combos fs -> s1
haven't test laranoa

**Comment by haukist** [comment]
I mean s1 -> fs

**Comment by b1ueb1ues** [comment]
I mean sarisse fs->s1->fs keep comboes

**Comment by haukist** [comment]
Hmm... For Sarisse I was just holding a bit longer, but I still can't do it with Laranoa.

**Comment by b1ueb1ues** [comment]
it make sense lara can't do that
