### ISSUE TITLE
Energy skill modifier

### ISSUE THREAD

**Issue by Totakeke** [b1ueb1ues/dl#4]
Saw in your code that energy is modified by 40%, is this something you have tested? Didn't see anything in mechanics either. The official news stated that the mod should be 50% so curious if you have proven it to be otherwise. 

https://dragalialost.com/en/news/event/2357
`■About the new "Energy" feature
"Energy" is a special kind of buff which upgrades certain skills once enough energy levels have been accumulated.
Once an adventurer's energy level reaches level 5, they will become "energized", and their next attack skill or recovery skill will be upgraded to deal 50% more damage or recover 50% more health respectively!`

**Comment by b1ueb1ues** [comment]
tested, should be 50%

**Comment by b1ueb1ues** [comment]
someone have tested that say it is 40%, so still not confirmed

**Comment by b1ueb1ues** [comment]
energized = ( 1 + skill damage passive + 0.5)/(1+skill damage passive)
So if you have an 25% skill damage WP, then energized=40%boost

need to change the code to calculate that more accurate

**Comment by b1ueb1ues** [comment]
have changed energy boost to 0.5/(1+passive_skill_damage_mod)
