### ISSUE TITLE
No module named 'floatsingle'?

### ISSUE THREAD

**Issue by betairylia** [b1ueb1ues/dl#41]
Sorry for this nearly stupid question but quite confusing about how it works.
Could you clearify the dependencies and the required python version in readme.md?
Please forgive me if I miss read anything ...

env:

ubuntu 18.04
python 3.6.7 with anaconda 4.5.11

running e.g. `python adv/mikoto.py 2 180 krdb` gives:
```
Traceback (most recent call last):  
  File "adv/mikoto.py", line 2, in <module>
    from adv import *
  File "adv/__init__.py", line 1, in <module>
    from core.advbase import *
  File "core/advbase.py", line 13, in <module>
    import floatsingle
ModuleNotFoundError: No module named 'floatsingle'
```

`pip install floatsingle` cannot found related package ... (x

**Comment by b1ueb1ues** [comment]
problem caused by base path difference between python3 and python2
fixed, you can update now.

**Comment by betairylia** [comment]
Thanks for the reply and fix!
